version: '3.8'

services:
  vault:
    image: vault:1.6.0
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
    restart: unless-stopped
    ports:
      - 8200:8200
